// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(NinjaContext))]
    [Migration("20231016180341_UpdatePriceToINt")]
    partial class UpdatePriceToINt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.Gear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gear");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agility = 5,
                            Category = 0,
                            Intelligence = 6,
                            Name = "Sample Gear 1",
                            Price = 233,
                            Strength = 4
                        },
                        new
                        {
                            Id = 2,
                            Agility = 7,
                            Category = 1,
                            Intelligence = 4,
                            Name = "Sample Gear 2",
                            Price = 250,
                            Strength = 8
                        },
                        new
                        {
                            Id = 3,
                            Agility = 4,
                            Category = 3,
                            Intelligence = 2,
                            Name = "Sample Gear 3",
                            Price = 220,
                            Strength = 4
                        },
                        new
                        {
                            Id = 4,
                            Agility = 12,
                            Category = 2,
                            Intelligence = 7,
                            Name = "Sample Gear 4",
                            Price = 110,
                            Strength = 14
                        },
                        new
                        {
                            Id = 5,
                            Agility = 5,
                            Category = 4,
                            Intelligence = 3,
                            Name = "Sample Gear 5",
                            Price = 90,
                            Strength = 10
                        },
                        new
                        {
                            Id = 6,
                            Agility = 10,
                            Category = 5,
                            Intelligence = 8,
                            Name = "Sample Gear 6",
                            Price = 90,
                            Strength = 12
                        });
                });

            modelBuilder.Entity("Data.Models.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Gold")
                        .HasMaxLength(5)
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");
                });

            modelBuilder.Entity("Data.Models.NinjaGear", b =>
                {
                    b.Property<int>("NinjaId")
                        .HasColumnType("int");

                    b.Property<int>("GearId")
                        .HasColumnType("int");

                    b.HasKey("NinjaId", "GearId");

                    b.HasIndex("GearId");

                    b.ToTable("NinjaGear");
                });

            modelBuilder.Entity("Data.Models.NinjaGear", b =>
                {
                    b.HasOne("Data.Models.Gear", "Gear")
                        .WithMany("Ninja")
                        .HasForeignKey("GearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Ninja", "Ninja")
                        .WithMany("Gear")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gear");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("Data.Models.Gear", b =>
                {
                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("Data.Models.Ninja", b =>
                {
                    b.Navigation("Gear");
                });
#pragma warning restore 612, 618
        }
    }
}
