// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(NinjaContext))]
    [Migration("20231020135726_UpdateTransactionsTable")]
    partial class UpdateTransactionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.Gear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gear");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agility = 5,
                            Category = 0,
                            Intelligence = 2,
                            Name = "Gold Helmet",
                            Price = 70,
                            Strength = 15
                        },
                        new
                        {
                            Id = 2,
                            Agility = 10,
                            Category = 0,
                            Intelligence = 12,
                            Name = "Iron Helmet",
                            Price = 150,
                            Strength = 20
                        },
                        new
                        {
                            Id = 3,
                            Agility = 15,
                            Category = 0,
                            Intelligence = 16,
                            Name = "Diamond Helmet",
                            Price = 220,
                            Strength = 30
                        },
                        new
                        {
                            Id = 4,
                            Agility = 2,
                            Category = 1,
                            Intelligence = 1,
                            Name = "Gold Chestplate",
                            Price = 150,
                            Strength = 3
                        },
                        new
                        {
                            Id = 5,
                            Agility = 16,
                            Category = 1,
                            Intelligence = 20,
                            Name = "Iron Chestplate",
                            Price = 225,
                            Strength = 9
                        },
                        new
                        {
                            Id = 6,
                            Agility = 5,
                            Category = 1,
                            Intelligence = 8,
                            Name = "Diamond Chestplate",
                            Price = 275,
                            Strength = 15
                        },
                        new
                        {
                            Id = 7,
                            Agility = 14,
                            Category = 2,
                            Intelligence = 13,
                            Name = "Gold Sword",
                            Price = 150,
                            Strength = 18
                        },
                        new
                        {
                            Id = 8,
                            Agility = 18,
                            Category = 2,
                            Intelligence = 16,
                            Name = "Iron Sword",
                            Price = 205,
                            Strength = 25
                        },
                        new
                        {
                            Id = 9,
                            Agility = 23,
                            Category = 2,
                            Intelligence = 20,
                            Name = "Diamond Sword",
                            Price = 265,
                            Strength = 31
                        },
                        new
                        {
                            Id = 10,
                            Agility = 5,
                            Category = 3,
                            Intelligence = 3,
                            Name = "Gold Boots",
                            Price = 60,
                            Strength = 6
                        },
                        new
                        {
                            Id = 11,
                            Agility = 10,
                            Category = 3,
                            Intelligence = 6,
                            Name = "Iron Boots",
                            Price = 100,
                            Strength = 12
                        },
                        new
                        {
                            Id = 12,
                            Agility = 7,
                            Category = 3,
                            Intelligence = 8,
                            Name = "Diamond Boots",
                            Price = 120,
                            Strength = 16
                        },
                        new
                        {
                            Id = 13,
                            Agility = 3,
                            Category = 4,
                            Intelligence = 1,
                            Name = "Gold Ring",
                            Price = 40,
                            Strength = 2
                        },
                        new
                        {
                            Id = 14,
                            Agility = 4,
                            Category = 4,
                            Intelligence = 2,
                            Name = "Iron Ring",
                            Price = 60,
                            Strength = 6
                        },
                        new
                        {
                            Id = 15,
                            Agility = 5,
                            Category = 4,
                            Intelligence = 4,
                            Name = "Diamond Ring",
                            Price = 80,
                            Strength = 9
                        },
                        new
                        {
                            Id = 16,
                            Agility = 10,
                            Category = 5,
                            Intelligence = 1,
                            Name = "Gold Necklace",
                            Price = 25,
                            Strength = 11
                        },
                        new
                        {
                            Id = 17,
                            Agility = 20,
                            Category = 5,
                            Intelligence = 8,
                            Name = "Iron Necklace",
                            Price = 50,
                            Strength = 18
                        },
                        new
                        {
                            Id = 18,
                            Agility = 30,
                            Category = 5,
                            Intelligence = 24,
                            Name = "Diamond Necklace",
                            Price = 75,
                            Strength = 24
                        });
                });

            modelBuilder.Entity("Data.Models.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gold = 120,
                            Name = "Sensei"
                        },
                        new
                        {
                            Id = 2,
                            Gold = 100,
                            Name = "Naruto"
                        },
                        new
                        {
                            Id = 3,
                            Gold = 100,
                            Name = "Sasuke"
                        },
                        new
                        {
                            Id = 4,
                            Gold = 100,
                            Name = "Sakura"
                        });
                });

            modelBuilder.Entity("Data.Models.NinjaGear", b =>
                {
                    b.Property<int>("NinjaId")
                        .HasColumnType("int");

                    b.Property<int>("GearId")
                        .HasColumnType("int");

                    b.HasKey("NinjaId", "GearId");

                    b.HasIndex("GearId");

                    b.ToTable("NinjaGear");
                });

            modelBuilder.Entity("Data.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("GearId")
                        .HasColumnType("int");

                    b.Property<int?>("NinjaId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GearId");

                    b.HasIndex("NinjaId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Data.Models.NinjaGear", b =>
                {
                    b.HasOne("Data.Models.Gear", "Gear")
                        .WithMany("NinjaGear")
                        .HasForeignKey("GearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Ninja", "Ninja")
                        .WithMany("NinjaGear")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gear");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("Data.Models.Transaction", b =>
                {
                    b.HasOne("Data.Models.Gear", "Gear")
                        .WithMany("Transactions")
                        .HasForeignKey("GearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Ninja", "Ninja")
                        .WithMany("Transactions")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Gear");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("Data.Models.Gear", b =>
                {
                    b.Navigation("NinjaGear");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Data.Models.Ninja", b =>
                {
                    b.Navigation("NinjaGear");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
